apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/capmox-serving-cert'
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: cluster-api-provider-proxmox
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/part-of: cluster-api-provider-proxmox
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    application.giantswarm.io/branch: '{{ .Values.project.branch }}'
    application.giantswarm.io/commit: '{{ .Values.project.commit }}'
    cluster.x-k8s.io/provider: infrastructure-proxmox
    helm.sh/chart: '{{ .Chart.Name }}'
  name: capmox-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: capmox-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha1-proxmoxcluster
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.proxmoxcluster.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - proxmoxclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: capmox-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha1-proxmoxmachine
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.proxmoxmachine.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - proxmoxmachines
  sideEffects: None
