version: 2.1
orbs:
  architect: giantswarm/architect@5.1.1

workflows:
  package-and-push-chart-on-tag:
    jobs:
      # Ensure that for every commit
      # there is an app version in the test catalog.
      - architect/push-to-app-catalog:
          context: architect
          name: push-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "cluster-api-provider-proxmox"
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: proxmox-app-collection
          context: "architect"
          app_name: "cluster-api-provider-proxmox"
          app_collection_repo: "proxmox-app-collection"
          requires:
            - push-to-control-plane-app-catalog
          # Trigger job on git tag.
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
