apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: '{{ .Release.Namespace }}'

resources:
  - input/infrastructure-components.yaml
  - extras/ciliumnetworkpolicy-capmox-controller-manager.yaml
  - extras/networkpolicy-capmox-controller-manager.yaml

transformers:
  - patches/common-labels.yaml
  - patches/clusterctl-labels.yaml

patchesStrategicMerge:
  - patches/delete-namespace.yaml
  - patches/certificate.yaml
  - patches/webhook-certificate.yaml
  - patches/delete-issuer.yaml
  - patches/deployment-resources.yaml
  - patches/cluster-role-binding.yaml
  - patches/role-binding.yaml

patches:
  - path: patches/crd_cainjection.yaml
    target:
      kind: CustomResourceDefinition
      labelSelector: cluster.x-k8s.io/provider=infrastructure-proxmox
  - path: patches/crd_webhook.yaml
    target:
      kind: CustomResourceDefinition
      labelSelector: cluster.x-k8s.io/provider=infrastructure-proxmox
