---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: capmox-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/capmox-serving-cert"
